apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: chunkvault
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: chunkvault
data:
  chunkvault-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "ChunkVault Monitoring Dashboard",
        "tags": ["chunkvault", "storage", "monitoring"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(chunkvault_requests_total[5m])",
                "legendFormat": "{{method}} {{endpoint}}"
              }
            ],
            "yAxes": [
              {
                "label": "Requests/sec",
                "min": 0
              }
            ],
            "xAxis": {
              "mode": "time"
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(chunkvault_request_duration_seconds_bucket[5m]))",
                "legendFormat": "95th percentile"
              },
              {
                "expr": "histogram_quantile(0.50, rate(chunkvault_request_duration_seconds_bucket[5m]))",
                "legendFormat": "50th percentile"
              }
            ],
            "yAxes": [
              {
                "label": "Seconds",
                "min": 0
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "Files Uploaded",
            "type": "stat",
            "targets": [
              {
                "expr": "chunkvault_files_uploaded_total",
                "legendFormat": "Total Files"
              }
            ],
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 0,
              "y": 8
            }
          },
          {
            "id": 4,
            "title": "Files Downloaded",
            "type": "stat",
            "targets": [
              {
                "expr": "chunkvault_files_downloaded_total",
                "legendFormat": "Total Downloads"
              }
            ],
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 6,
              "y": 8
            }
          },
          {
            "id": 5,
            "title": "Chunks Stored",
            "type": "stat",
            "targets": [
              {
                "expr": "chunkvault_chunks_stored_total",
                "legendFormat": "Total Chunks"
              }
            ],
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 12,
              "y": 8
            }
          },
          {
            "id": 6,
            "title": "Active Connections",
            "type": "stat",
            "targets": [
              {
                "expr": "chunkvault_active_connections",
                "legendFormat": "Active Connections"
              }
            ],
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 18,
              "y": 8
            }
          },
          {
            "id": 7,
            "title": "Storage Node Health",
            "type": "graph",
            "targets": [
              {
                "expr": "chunkvault_storage_node_health",
                "legendFormat": "Node {{node_id}}"
              }
            ],
            "yAxes": [
              {
                "label": "Health Status",
                "min": 0,
                "max": 1
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 12
            }
          },
          {
            "id": 8,
            "title": "Cache Hit Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(chunkvault_cache_hits_total[5m]) / (rate(chunkvault_cache_hits_total[5m]) + rate(chunkvault_cache_misses_total[5m]))",
                "legendFormat": "{{cache_type}}"
              }
            ],
            "yAxes": [
              {
                "label": "Hit Rate",
                "min": 0,
                "max": 1
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 12
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "5s"
      }
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: chunkvault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: chunkvault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: chunkvault
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
