apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-node-1-pvc
  namespace: chunkvault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-node-2-pvc
  namespace: chunkvault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-node-3-pvc
  namespace: chunkvault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-node-1
  namespace: chunkvault
spec:
  serviceName: storage-node-1
  replicas: 1
  selector:
    matchLabels:
      app: storage-node-1
  template:
    metadata:
      labels:
        app: storage-node-1
    spec:
      containers:
        - name: storage-node
          image: chunkvault:latest
          command: ["python", "storage_node.py"]
          ports:
            - containerPort: 8001
          env:
            - name: NODE_ID
              value: "node-1"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8001"
            - name: STORAGE_PATH
              value: "/app/storage"
          volumeMounts:
            - name: storage
              mountPath: /app/storage
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage-node-1-pvc

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-node-2
  namespace: chunkvault
spec:
  serviceName: storage-node-2
  replicas: 1
  selector:
    matchLabels:
      app: storage-node-2
  template:
    metadata:
      labels:
        app: storage-node-2
    spec:
      containers:
        - name: storage-node
          image: chunkvault:latest
          command: ["python", "storage_node.py"]
          ports:
            - containerPort: 8002
          env:
            - name: NODE_ID
              value: "node-2"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8002"
            - name: STORAGE_PATH
              value: "/app/storage"
          volumeMounts:
            - name: storage
              mountPath: /app/storage
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage-node-2-pvc

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-node-3
  namespace: chunkvault
spec:
  serviceName: storage-node-3
  replicas: 1
  selector:
    matchLabels:
      app: storage-node-3
  template:
    metadata:
      labels:
        app: storage-node-3
    spec:
      containers:
        - name: storage-node
          image: chunkvault:latest
          command: ["python", "storage_node.py"]
          ports:
            - containerPort: 8003
          env:
            - name: NODE_ID
              value: "node-3"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8003"
            - name: STORAGE_PATH
              value: "/app/storage"
          volumeMounts:
            - name: storage
              mountPath: /app/storage
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage-node-3-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: storage-node-1
  namespace: chunkvault
spec:
  selector:
    app: storage-node-1
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: storage-node-2
  namespace: chunkvault
spec:
  selector:
    app: storage-node-2
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: storage-node-3
  namespace: chunkvault
spec:
  selector:
    app: storage-node-3
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
