apiVersion: v1
kind: ConfigMap
metadata:
  name: chunkvault-config
  namespace: chunkvault
data:
  SECRET_KEY: "chunkvault-super-secret-key-change-in-production"
  DATABASE_URL: "postgresql://chunkvault:chunkvault@postgres:5432/chunkvault"
  REDIS_URL: "redis://redis:6379/0"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunkvault-api
  namespace: chunkvault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chunkvault-api
  template:
    metadata:
      labels:
        app: chunkvault-api
    spec:
      containers:
        - name: chunkvault-api
          image: chunkvault:latest
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: chunkvault-config
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: chunkvault-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: chunkvault-config
                  key: REDIS_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: chunkvault-api
  namespace: chunkvault
spec:
  selector:
    app: chunkvault-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chunkvault-api-hpa
  namespace: chunkvault
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chunkvault-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
