apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: chunkvault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: chunkvault:latest
          command:
            [
              "celery",
              "-A",
              "celery_app",
              "worker",
              "--loglevel=info",
              "--concurrency=4",
            ]
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: chunkvault-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: chunkvault-config
                  key: REDIS_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: chunkvault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: chunkvault:latest
          command: ["celery", "-A", "celery_app", "beat", "--loglevel=info"]
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: chunkvault-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: chunkvault-config
                  key: REDIS_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
